# permissions for end users to view alarms.
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: alarms-viewer-role
rules:
- apiGroups:
  - cloudwatch.anandnilkal.io
  resources:
  - alarms
  verbs:
  - get
  - list
  - watch
- apiGroups:
  - cloudwatch.anandnilkal.io
  resources:
  - alarms/status
  verbs:
  - get
