# permissions for end users to edit alarms.
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: alarms-editor-role
rules:
- apiGroups:
  - cloudwatch.anandnilkal.io
  resources:
  - alarms
  verbs:
  - create
  - delete
  - get
  - list
  - patch
  - update
  - watch
- apiGroups:
  - cloudwatch.anandnilkal.io
  resources:
  - alarms/status
  verbs:
  - get
