apiVersion: cloudwatch.anandnilkal.io/v1alpha1
kind: Alarms
metadata:
  name: alarms-sample
spec:
  # TODO(user): Add fields here
  name: alarms-sample
  operator: "GreaterThanThreshold"
  evaluationPeriod: 5
  alarmActions:
    - arn:aws:sns:us-west-2:374188005532:OpsGenie-alerts
  description: "test alarm creation"
  numDataPointsToAlarm: 5
  dimensions:
  - name: QueueName
    value: cloud-systems-Alert-Listener-Queue
  metricName: ApproximateNumberOfMessagesNotVisible
  statistics: Average
    #okActions:
    #- arn:aws:sns:us-west-2:374188005532:OpsGenie-alerts
    #metrics:
    #- id: test
    #accountId: test
    #expression: test
    #label: test
    #returnData: true
    #period: 10
    #metricStat:
    #  period: 10
    #  stat: test
    #  unit: test
    #  metric:
    #    dimensions:
    #    - name: test
    #      value: test
    #    metricName: test
    #    namespace: test
  namespace: AWS/SQS
  period: 60
  threshold: 10
