apiVersion: cloudwatch.anandnilkal.io/v1alpha1
kind: Alarms
metadata:
  name: alarms-sample
spec:
  # TODO(user): Add fields here
  region: us-east-1
  name: alarms-sample
  operator: "GreaterThanThreshold"
  evaluationPeriod: 5
  alarmActions: []
    #  - arn:aws:sns:us-west-2:374188005532:OpsGenie-alerts
  description: "test alarm creation"
  numDataPointsToAlarm: 5
  dimensions:
  - name: QueueName
    value: cloud-systems-Alert-Listener-Queue
  metricName: ApproximateNumberOfMessagesNotVisible
  statistics: Average
  namespace: AWS/SQS
  period: 60
  threshold: 10
  tags:
  - key: release
    value: test
  - key: namespace
    value: dev-group6
